PORTNAME=	function2
DISTVERSION=	4.2.3
PORTEPOCH=	1
CATEGORIES=	devel

MAINTAINER=	kyle@ambroffkao.com
COMMENT=	Provides fu2::function, an improved drop-in replacement for std::function
WWW=		https://github.com/Naios/function2

LICENSE=	BSL
LICENSE_FILE=	${WRKSRC}/LICENSE.txt

USE_GITHUB=	yes
GH_ACCOUNT=	Naios

USES=		cmake
CMAKE_OFF=	BUILD_TESTING
CMAKE_TESTING_ON=	BUILD_TESTING

.include <bsd.port.mk>
